// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// xMove //
// ----- //

#define xMove_wrap_target 0
#define xMove_wrap 3
#define xMove_pio_version 0

static const uint16_t xMove_program_instructions[] = {
            //     .wrap_target
    0xe03f, //  0: set    x, 31
    0x6001, //  1: out    pins, 1
    0x0041, //  2: jmp    x--, 1
    0xc020, //  3: irq    wait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program xMove_program = {
    .instructions = xMove_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = xMove_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config xMove_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + xMove_wrap_target, offset + xMove_wrap);
    return c;
}

#include "hardware/clocks.h"
/*! @brief           inits pio for x motor
 *  @param pio       the pio running program
 *  @param sm        state machine
 *  @param offset    offset calc'd in init
 *  @param pin       pin used as output
 *  @param freq      freq for clock div
 */
void xMove_program_init(PIO pio, uint sm, uint offset, uint pin, float freq) {
    pio_gpio_init(pio, pin); 
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_sm_config c = xMove_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin, 1);
    sm_config_set_out_shift(&c, false, true, 32); 
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX); //makes the fifo a single 8 entry fifo. How much is an entry? 4 words deep. How much is a word? IDK
    float div = clock_get_hz(clk_sys) / (freq * 4.0 );    
    sm_config_set_clkdiv(&c, div);                      
    pio_sm_init(pio, sm, offset, &c);
}

#endif

// ----- //
// yMove //
// ----- //

#define yMove_wrap_target 0
#define yMove_wrap 3
#define yMove_pio_version 0

static const uint16_t yMove_program_instructions[] = {
            //     .wrap_target
    0xe03f, //  0: set    x, 31
    0x6001, //  1: out    pins, 1
    0x0041, //  2: jmp    x--, 1
    0xc021, //  3: irq    wait 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program yMove_program = {
    .instructions = yMove_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = yMove_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config yMove_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + yMove_wrap_target, offset + yMove_wrap);
    return c;
}

#include "hardware/clocks.h"
/*! @brief           inits pio for y motor
 *  @param pio       the pio running program
 *  @param sm        state machine
 *  @param offset    offset calc'd in init
 *  @param pin       pin used as output
 *  @param freq      freq for clock div
 */
void yMove_program_init(PIO pio, uint sm, uint offset, uint pin, float freq) {
    pio_gpio_init(pio, pin); 
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_sm_config c = yMove_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin, 1);
    sm_config_set_out_shift(&c, false, true, 32); 
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX); //makes the fifo a single 8 entry fifo. How much is an entry? 4 words deep. How much is a word? IDK
    float div = clock_get_hz(clk_sys) / (freq * 4.0 );    
    sm_config_set_clkdiv(&c, div);                      
    pio_sm_init(pio, sm, offset, &c);
}

#endif

